[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[rpc_endpoints]
local = "${LOCALHOST_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"
optimism_goerli = "${OPTIMISM_GOERLI_RPC_URL}"
arbitrum_goerli = "${ARBITRUM_GOERLI_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config